//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopWorkspace.Main.Command {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevelopWorkspace.Main.Command.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Show information about EDI 的本地化字符串。
        /// </summary>
        public static string CMD_APP_About_Description {
            get {
                return ResourceManager.GetString("CMD_APP_About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close document 的本地化字符串。
        /// </summary>
        public static string CMD_APP_CloseDoc_Description {
            get {
                return ResourceManager.GetString("CMD_APP_CloseDoc_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit application 的本地化字符串。
        /// </summary>
        public static string CMD_App_Exit_Describtion {
            get {
                return ResourceManager.GetString("CMD_App_Exit_Describtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text to HTML 的本地化字符串。
        /// </summary>
        public static string CMD_APP_ExportTextToHTML_Description {
            get {
                return ResourceManager.GetString("CMD_APP_ExportTextToHTML_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UML to Image 的本地化字符串。
        /// </summary>
        public static string CMD_APP_ExportUMLToImage_Description {
            get {
                return ResourceManager.GetString("CMD_APP_ExportUMLToImage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open file ... 的本地化字符串。
        /// </summary>
        public static string CMD_APP_Open_Description {
            get {
                return ResourceManager.GetString("CMD_APP_Open_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open URL ... 的本地化字符串。
        /// </summary>
        public static string CMD_APP_OpenURL_Description {
            get {
                return ResourceManager.GetString("CMD_APP_OpenURL_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save All ... 的本地化字符串。
        /// </summary>
        public static string CMD_APP_SaveAll_Description {
            get {
                return ResourceManager.GetString("CMD_APP_SaveAll_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Start Page 的本地化字符串。
        /// </summary>
        public static string CMD_APP_ShowStartPage_Description {
            get {
                return ResourceManager.GetString("CMD_APP_ShowStartPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle display of optional elements like statusbar and toolbar. 的本地化字符串。
        /// </summary>
        public static string CMD_APP_ToggleOptimizeWorkspace_Description {
            get {
                return ResourceManager.GetString("CMD_APP_ToggleOptimizeWorkspace_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change theme 的本地化字符串。
        /// </summary>
        public static string CMD_APP_ViewTheme_Description {
            get {
                return ResourceManager.GetString("CMD_APP_ViewTheme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add MRU Entry 的本地化字符串。
        /// </summary>
        public static string CMD_MRU_AddEntry_Description {
            get {
                return ResourceManager.GetString("CMD_MRU_AddEntry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin or unpin an MRU entry 的本地化字符串。
        /// </summary>
        public static string CMD_MRU_Pin_Description {
            get {
                return ResourceManager.GetString("CMD_MRU_Pin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove MRU Entry 的本地化字符串。
        /// </summary>
        public static string CMD_MRU_RemoveEntry_Description {
            get {
                return ResourceManager.GetString("CMD_MRU_RemoveEntry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch off syntax highlighting for current file 的本地化字符串。
        /// </summary>
        public static string CMD_TXT_DisableHighlighting_Description {
            get {
                return ResourceManager.GetString("CMD_TXT_DisableHighlighting_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find specific text in a document 的本地化字符串。
        /// </summary>
        public static string CMD_TXT_FindNext_Description {
            get {
                return ResourceManager.GetString("CMD_TXT_FindNext_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find next occurrence of specific text in a document 的本地化字符串。
        /// </summary>
        public static string CMD_TXT_FindNextText_Description {
            get {
                return ResourceManager.GetString("CMD_TXT_FindNextText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find previous occurrence of specific text in a document 的本地化字符串。
        /// </summary>
        public static string CMD_TXT_FindPreviousText_Description {
            get {
                return ResourceManager.GetString("CMD_TXT_FindPreviousText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find and replace a specific text in a document 的本地化字符串。
        /// </summary>
        public static string CMD_TXT_FindReplaceText_Description {
            get {
                return ResourceManager.GetString("CMD_TXT_FindReplaceText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to a specific line in a document 的本地化字符串。
        /// </summary>
        public static string CMD_TXT_GotoLine_Description {
            get {
                return ResourceManager.GetString("CMD_TXT_GotoLine_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code Completion: 的本地化字符串。
        /// </summary>
        public static string STR_ABOUT_CODE_COMPLETION {
            get {
                return ResourceManager.GetString("STR_ABOUT_CODE_COMPLETION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Docking Layout System: 的本地化字符串。
        /// </summary>
        public static string STR_ABOUT_DOCKING_LAYOUT {
            get {
                return ResourceManager.GetString("STR_ABOUT_DOCKING_LAYOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log4Net Viewer: 的本地化字符串。
        /// </summary>
        public static string STR_ABOUT_Log4NetViewer {
            get {
                return ResourceManager.GetString("STR_ABOUT_Log4NetViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A Text and UML Editor. 的本地化字符串。
        /// </summary>
        public static string STR_ABOUT_MSG {
            get {
                return ResourceManager.GetString("STR_ABOUT_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _OK 的本地化字符串。
        /// </summary>
        public static string STR_ABOUT_OK_BUTTON {
            get {
                return ResourceManager.GetString("STR_ABOUT_OK_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Editor: 的本地化字符串。
        /// </summary>
        public static string STR_ABOUT_TextEditor {
            get {
                return ResourceManager.GetString("STR_ABOUT_TextEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string STR_ABOUT_Version {
            get {
                return ResourceManager.GetString("STR_ABOUT_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version Info 的本地化字符串。
        /// </summary>
        public static string STR_ABOUT_VERSION_INFO_LABEL {
            get {
                return ResourceManager.GetString("STR_ABOUT_VERSION_INFO_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The directory &apos;{0}&apos; does not exist or cannot be accessed. 的本地化字符串。
        /// </summary>
        public static string STR_ACCESS_DIRECTORY_ERROR {
            get {
                return ResourceManager.GetString("STR_ACCESS_DIRECTORY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy path to clipboard 的本地化字符串。
        /// </summary>
        public static string STR_AppCommand_CopyFileURLToClipboard {
            get {
                return ResourceManager.GetString("STR_AppCommand_CopyFileURLToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy the path of this document into the Windows Clipboard 的本地化字符串。
        /// </summary>
        public static string STR_AppCommand_CopyFileURLToClipboard_TT {
            get {
                return ResourceManager.GetString("STR_AppCommand_CopyFileURLToClipboard_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Containing folder... 的本地化字符串。
        /// </summary>
        public static string STR_AppCommand_OpenContainingFolder {
            get {
                return ResourceManager.GetString("STR_AppCommand_OpenContainingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the folder that contains this document in Windows Explorer 的本地化字符串。
        /// </summary>
        public static string STR_AppCommand_OpenContainingFolder_TT {
            get {
                return ResourceManager.GetString("STR_AppCommand_OpenContainingFolder_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set path in Explorer tool window 的本地化字符串。
        /// </summary>
        public static string STR_AppCommand_SyncPathToExplorerCommand {
            get {
                return ResourceManager.GetString("STR_AppCommand_SyncPathToExplorerCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display document in Explorer tool window 的本地化字符串。
        /// </summary>
        public static string STR_AppCommand_SyncPathToExplorerCommand_TT {
            get {
                return ResourceManager.GetString("STR_AppCommand_SyncPathToExplorerCommand_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string STR_Category_Error {
            get {
                return ResourceManager.GetString("STR_Category_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        public static string STR_Category_Information {
            get {
                return ResourceManager.GetString("STR_Category_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internal Error 的本地化字符串。
        /// </summary>
        public static string STR_Category_InternalError {
            get {
                return ResourceManager.GetString("STR_Category_InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown Internal Error 的本地化字符串。
        /// </summary>
        public static string STR_Category_Unknown_Internal_Error {
            get {
                return ResourceManager.GetString("STR_Category_Unknown_Internal_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown Error 的本地化字符串。
        /// </summary>
        public static string STR_Category_UnknownError {
            get {
                return ResourceManager.GetString("STR_Category_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string STR_Category_Warning {
            get {
                return ResourceManager.GetString("STR_Category_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply Indentation Strategy 的本地化字符串。
        /// </summary>
        public static string STR_Cmd__ApplyTextIndentationStrategy {
            get {
                return ResourceManager.GetString("STR_Cmd__ApplyTextIndentationStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert text to lower case 的本地化字符串。
        /// </summary>
        public static string STR_Cmd__ConvertTextToLowerCase {
            get {
                return ResourceManager.GetString("STR_Cmd__ConvertTextToLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert to Title Case 的本地化字符串。
        /// </summary>
        public static string STR_Cmd__ConvertTextToTitleCase {
            get {
                return ResourceManager.GetString("STR_Cmd__ConvertTextToTitleCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invert Case 的本地化字符串。
        /// </summary>
        public static string STR_Cmd__InvertTextCase {
            get {
                return ResourceManager.GetString("STR_Cmd__InvertTextCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collapse text foldings 的本地化字符串。
        /// </summary>
        public static string STR_Cmd_CollapseTextFoldings {
            get {
                return ResourceManager.GetString("STR_Cmd_CollapseTextFoldings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert Leading Spaces to Tabs 的本地化字符串。
        /// </summary>
        public static string STR_Cmd_ConvertLeadingSpaces {
            get {
                return ResourceManager.GetString("STR_Cmd_ConvertLeadingSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert Leading Tabs to Spaces 的本地化字符串。
        /// </summary>
        public static string STR_Cmd_ConvertLeadingTabsToSpaces {
            get {
                return ResourceManager.GetString("STR_Cmd_ConvertLeadingTabsToSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert Spaces to Tabs 的本地化字符串。
        /// </summary>
        public static string STR_CMD_ConvertSpacesToTabs {
            get {
                return ResourceManager.GetString("STR_CMD_ConvertSpacesToTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert Tabs to Spaces 的本地化字符串。
        /// </summary>
        public static string STR_CMD_ConvertTabsToSpaces {
            get {
                return ResourceManager.GetString("STR_CMD_ConvertTabsToSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert text to upper case 的本地化字符串。
        /// </summary>
        public static string STR_Cmd_ConvertTextToUpperCase {
            get {
                return ResourceManager.GetString("STR_Cmd_ConvertTextToUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand text foldings 的本地化字符串。
        /// </summary>
        public static string STR_Cmd_ExpandTextFoldings {
            get {
                return ResourceManager.GetString("STR_Cmd_ExpandTextFoldings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Leading White Spaces 的本地化字符串。
        /// </summary>
        public static string STR_CMD_RemoveLeadingWhiteSpace {
            get {
                return ResourceManager.GetString("STR_CMD_RemoveLeadingWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Trailing White Space 的本地化字符串。
        /// </summary>
        public static string STR_CMD_RemoveTrailingWhiteSpace {
            get {
                return ResourceManager.GetString("STR_CMD_RemoveTrailingWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Close {
            get {
                return ResourceManager.GetString("STR_CmdName_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Copy {
            get {
                return ResourceManager.GetString("STR_CmdName_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy selected item 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Copy_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Copy_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Cut {
            get {
                return ResourceManager.GetString("STR_CmdName_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut selected item 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Cut_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Cut_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Delete {
            get {
                return ResourceManager.GetString("STR_CmdName_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete selected item 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Delete_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Delete_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Line 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_DeleteLine {
            get {
                return ResourceManager.GetString("STR_CmdName_DeleteLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deletes the current line of text 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_DeleteLine_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_DeleteLine_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Edit 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Edit {
            get {
                return ResourceManager.GetString("STR_CmdName_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Exit {
            get {
                return ResourceManager.GetString("STR_CmdName_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Export {
            get {
                return ResourceManager.GetString("STR_CmdName_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert data into a file format that is suitable to other applications. 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Export_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Export_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _File 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_File {
            get {
                return ResourceManager.GetString("STR_CmdName_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Explorer Tool Window 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_FileExplorer_TW {
            get {
                return ResourceManager.GetString("STR_CmdName_FileExplorer_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Find {
            get {
                return ResourceManager.GetString("STR_CmdName_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to line... 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_GotoLine {
            get {
                return ResourceManager.GetString("STR_CmdName_GotoLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Help 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Help {
            get {
                return ResourceManager.GetString("STR_CmdName_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Help_About {
            get {
                return ResourceManager.GetString("STR_CmdName_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log4Net Message Tool Window 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Log4Net_Message_TW {
            get {
                return ResourceManager.GetString("STR_CmdName_Log4Net_Message_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log4Net Tool Window 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Log4Net_TW {
            get {
                return ResourceManager.GetString("STR_CmdName_Log4Net_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_New {
            get {
                return ResourceManager.GetString("STR_CmdName_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Document 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_New_Text {
            get {
                return ResourceManager.GetString("STR_CmdName_New_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create a text file 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_New_Text_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_New_Text_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UML Document 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_New_UML {
            get {
                return ResourceManager.GetString("STR_CmdName_New_UML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create a uml file 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_New_UML_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_New_UML_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Open {
            get {
                return ResourceManager.GetString("STR_CmdName_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log4Net Document 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Open_Log4Net {
            get {
                return ResourceManager.GetString("STR_CmdName_Open_Log4Net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open a Log4Net file 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Open_Log4Net_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Open_Log4Net_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Document 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Open_Text {
            get {
                return ResourceManager.GetString("STR_CmdName_Open_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open a text file 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Open_Text_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Open_Text_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UML Document 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Open_UML {
            get {
                return ResourceManager.GetString("STR_CmdName_Open_UML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open an UML file 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Open_UML_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Open_UML_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Paste {
            get {
                return ResourceManager.GetString("STR_CmdName_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste item from Windows clipboard 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Paste_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Paste_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties Tool Window 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Properties_TW {
            get {
                return ResourceManager.GetString("STR_CmdName_Properties_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent Documents 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_RecentFiles {
            get {
                return ResourceManager.GetString("STR_CmdName_RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent Files Tool Window 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_RecentFiles_TW {
            get {
                return ResourceManager.GetString("STR_CmdName_RecentFiles_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Redo {
            get {
                return ResourceManager.GetString("STR_CmdName_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo last undo 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Redo_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Redo_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Replace {
            get {
                return ResourceManager.GetString("STR_CmdName_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Save {
            get {
                return ResourceManager.GetString("STR_CmdName_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save current file 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Save_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Save_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As ... 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_SaveAs {
            get {
                return ResourceManager.GetString("STR_CmdName_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save file as certain type and in certain location 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_SaveAs_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_SaveAs_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select All 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_SelectAll {
            get {
                return ResourceManager.GetString("STR_CmdName_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select all items 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_SelectAll_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_SelectAll_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings... 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Settings {
            get {
                return ResourceManager.GetString("STR_CmdName_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Themes 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Themes {
            get {
                return ResourceManager.GetString("STR_CmdName_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Tools 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Tools {
            get {
                return ResourceManager.GetString("STR_CmdName_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Undo {
            get {
                return ResourceManager.GetString("STR_CmdName_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo last edit 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_Undo_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Undo_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _View 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_View {
            get {
                return ResourceManager.GetString("STR_CmdName_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optimize Workspace 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_View_OptimizedWorkSpace {
            get {
                return ResourceManager.GetString("STR_CmdName_View_OptimizedWorkSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Page 的本地化字符串。
        /// </summary>
        public static string STR_CmdName_View_Start_Page {
            get {
                return ResourceManager.GetString("STR_CmdName_View_Start_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contributors 的本地化字符串。
        /// </summary>
        public static string STR_Contributors_Label {
            get {
                return ResourceManager.GetString("STR_Contributors_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your input is not sufficient. Correct the following problems or click Cancel. 的本地化字符串。
        /// </summary>
        public static string STR_DIALOG_INPUT_PROBLEM_CAPTION {
            get {
                return ResourceManager.GetString("STR_DIALOG_INPUT_PROBLEM_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INS 的本地化字符串。
        /// </summary>
        public static string STR_EDIT_MODE_INSERT {
            get {
                return ResourceManager.GetString("STR_EDIT_MODE_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OVR 的本地化字符串。
        /// </summary>
        public static string STR_EDIT_MODE_TYPEOVER {
            get {
                return ResourceManager.GetString("STR_EDIT_MODE_TYPEOVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Loading file 的本地化字符串。
        /// </summary>
        public static string STR_ERROR_LOADING_FILE_CAPTION {
            get {
                return ResourceManager.GetString("STR_ERROR_LOADING_FILE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file:
        ///&apos;{0}&apos;
        ///
        ///does not exist or cannot be loaded.
        ///Do you want to remove this file from the list of recent files? 的本地化字符串。
        /// </summary>
        public static string STR_ERROR_LOADING_FILE_MSG {
            get {
                return ResourceManager.GetString("STR_ERROR_LOADING_FILE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTML Files (*.html, *.htm)|*.html;*.htm|
        ///All Files (*.*)|*.* 的本地化字符串。
        /// </summary>
        public static string STR_ExportHTMLFileFilter {
            get {
                return ResourceManager.GetString("STR_ExportHTMLFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Untitled 的本地化字符串。
        /// </summary>
        public static string STR_FILE_DEFAULTNAME {
            get {
                return ResourceManager.GetString("STR_FILE_DEFAULTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error finding file 的本地化字符串。
        /// </summary>
        public static string STR_FILE_FINDING_CAPTION {
            get {
                return ResourceManager.GetString("STR_FILE_FINDING_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error has occurred 的本地化字符串。
        /// </summary>
        public static string STR_FILE_OPEN_ERROR_MSG_CAPTION {
            get {
                return ResourceManager.GetString("STR_FILE_OPEN_ERROR_MSG_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This file cannot be edited because you do not have write access.
        ///Change the file access permissions or save the file in a different location if you want to edit it. 的本地化字符串。
        /// </summary>
        public static string STR_FILE_READONLY_REASON_NO_WRITE_PERMISSION {
            get {
                return ResourceManager.GetString("STR_FILE_READONLY_REASON_NO_WRITE_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This file cannot be edited because another process is currently writing to it.
        ///End the other process and re-open the file or save the file in a different location if you want to edit it. 的本地化字符串。
        /// </summary>
        public static string STR_FILE_READONLY_REASON_USED_BY_OTHER_PROCESS {
            get {
                return ResourceManager.GetString("STR_FILE_READONLY_REASON_USED_BY_OTHER_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Name 的本地化字符串。
        /// </summary>
        public static string STR_FILESTATES_FileName {
            get {
                return ResourceManager.GetString("STR_FILESTATES_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Path 的本地化字符串。
        /// </summary>
        public static string STR_FILESTATES_FilePath {
            get {
                return ResourceManager.GetString("STR_FILESTATES_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Size 的本地化字符串。
        /// </summary>
        public static string STR_FILESTATES_FileSize {
            get {
                return ResourceManager.GetString("STR_FILESTATES_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date and time of last modification. 的本地化字符串。
        /// </summary>
        public static string STR_FILESTATES_LASTMODIFICATION {
            get {
                return ResourceManager.GetString("STR_FILESTATES_LASTMODIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Files (*.*)|*.* 的本地化字符串。
        /// </summary>
        public static string STR_FileType_FileFilter_AllFiles {
            get {
                return ResourceManager.GetString("STR_FileType_FileFilter_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C# Files (*.cs)|*.cs 的本地化字符串。
        /// </summary>
        public static string STR_FileType_FileFilter_CSharp {
            get {
                return ResourceManager.GetString("STR_FileType_FileFilter_CSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTML Files (*.htm,*.html,*.css,*.js)|*.htm;*.html;*.css;*.js 的本地化字符串。
        /// </summary>
        public static string STR_FileType_FileFilter_HTML {
            get {
                return ResourceManager.GetString("STR_FileType_FileFilter_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;log4net XML output (*.log4j,*.xml)|*.log4j;*.xml|All Files (*.*)|*.*&quot; 的本地化字符串。
        /// </summary>
        public static string STR_FileType_FileFilter_Log4j {
            get {
                return ResourceManager.GetString("STR_FileType_FileFilter_Log4j", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 log4net XML output (*.log4j,*.log,*.txt,*.xml)|*.log4j;*.log;*.txt;*.xml 的本地化字符串。
        /// </summary>
        public static string STR_FileType_FileFilter_Log4NetPlusText {
            get {
                return ResourceManager.GetString("STR_FileType_FileFilter_Log4NetPlusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Structured Query Language (*.sql) |*.sql 的本地化字符串。
        /// </summary>
        public static string STR_FileType_FileFilter_SQL {
            get {
                return ResourceManager.GetString("STR_FileType_FileFilter_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Files (*.txt)|*.txt 的本地化字符串。
        /// </summary>
        public static string STR_FileType_FileFilter_TextFiles {
            get {
                return ResourceManager.GetString("STR_FileType_FileFilter_TextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unified Modeling Language (*.uml,*.xml)|*.uml;*.xml|All Files (*.*)|*.*&quot; 的本地化字符串。
        /// </summary>
        public static string STR_FileType_FileFilter_UML {
            get {
                return ResourceManager.GetString("STR_FileType_FileFilter_UML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find 的本地化字符串。
        /// </summary>
        public static string STR_FIND_BUTTON_CAPTION {
            get {
                return ResourceManager.GetString("STR_FIND_BUTTON_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find and Replace... 的本地化字符串。
        /// </summary>
        public static string STR_FIND_REPLACE_CAPTION {
            get {
                return ResourceManager.GetString("STR_FIND_REPLACE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you really want to replace all occurrences of &apos;{0}&apos; with &apos;{1}&apos;? 的本地化字符串。
        /// </summary>
        public static string STR_FINDREPLACE_ASK_REALLY_REPLACEEVERYTHING {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_ASK_REALLY_REPLACEEVERYTHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Case Sensitive 的本地化字符串。
        /// </summary>
        public static string STR_FINDREPLACE_CaseSensitive {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Document 的本地化字符串。
        /// </summary>
        public static string STR_FINDREPLACE_CURRENTDOC {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_CURRENTDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text to Find: 的本地化字符串。
        /// </summary>
        public static string STR_FINDREPLACE_FINDLABEL {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_FINDLABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find _Next 的本地化字符串。
        /// </summary>
        public static string STR_FINDREPLACE_FINDNEXT {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_FINDNEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match whole Word 的本地化字符串。
        /// </summary>
        public static string STR_FINDREPLACE_MatchWholeWord {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_MatchWholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Open Documents 的本地化字符串。
        /// </summary>
        public static string STR_FINDREPLACE_OPENDOCS {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_OPENDOCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string STR_FINDREPLACE_Options {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regular Expression 的本地化字符串。
        /// </summary>
        public static string STR_FINDREPLACE_RegularExpression {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Replace 的本地化字符串。
        /// </summary>
        public static string STR_FINDREPLACE_Replace {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace _All 的本地化字符串。
        /// </summary>
        public static string STR_FINDREPLACE_ReplaceAll {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace all 的本地化字符串。
        /// </summary>
        public static string STR_FINDREPLACE_ReplaceAll_Caption {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_ReplaceAll_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace with: 的本地化字符串。
        /// </summary>
        public static string STR_FINDREPLACE_ReplaceWith {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_ReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search up 的本地化字符串。
        /// </summary>
        public static string STR_FINDREPLACE_SearchBackWard {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_SearchBackWard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search in: 的本地化字符串。
        /// </summary>
        public static string STR_FINDREPLACE_SearchInLABEL {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_SearchInLABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wildcards 的本地化字符串。
        /// </summary>
        public static string STR_FINDREPLACE_Wildcards {
            get {
                return ResourceManager.GetString("STR_FINDREPLACE_Wildcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to Line ... 的本地化字符串。
        /// </summary>
        public static string STR_GOTO_LINE_CAPTION {
            get {
                return ResourceManager.GetString("STR_GOTO_LINE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Cancel 的本地化字符串。
        /// </summary>
        public static string STR_GOTOLINE_CANCEL_BUTTON {
            get {
                return ResourceManager.GetString("STR_GOTOLINE_CANCEL_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line 的本地化字符串。
        /// </summary>
        public static string STR_GOTOLINE_LINE_RANGE_LABEL {
            get {
                return ResourceManager.GetString("STR_GOTOLINE_LINE_RANGE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _OK 的本地化字符串。
        /// </summary>
        public static string STR_GOTOLINE_OK_BUTTON {
            get {
                return ResourceManager.GetString("STR_GOTOLINE_OK_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert or overtype text mode (switch on/of with insert key) 的本地化字符串。
        /// </summary>
        public static string STR_Insert_Overtype_Mode_TT {
            get {
                return ResourceManager.GetString("STR_Insert_Overtype_Mode_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Case 的本地化字符串。
        /// </summary>
        public static string STR_Label_TextCase {
            get {
                return ResourceManager.GetString("STR_Label_TextCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 White Spaces 的本地化字符串。
        /// </summary>
        public static string STR_Label_WhiteSpaces {
            get {
                return ResourceManager.GetString("STR_Label_WhiteSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delta t: 的本地化字符串。
        /// </summary>
        public static string STR_LOG4NET_DELTATIME {
            get {
                return ResourceManager.GetString("STR_LOG4NET_DELTATIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A log4net document can be used to view the XML output from a log4net logger session. 的本地化字符串。
        /// </summary>
        public static string STR_LOG4NET_DOCUMENTTAB_TT {
            get {
                return ResourceManager.GetString("STR_LOG4NET_DOCUMENTTAB_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter a log item Id to scroll the document view to its item. 的本地化字符串。
        /// </summary>
        public static string STR_LOG4NET_ENTERLOGID_TT {
            get {
                return ResourceManager.GetString("STR_LOG4NET_ENTERLOGID_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ALL 的本地化字符串。
        /// </summary>
        public static string STR_LOG4NET_FILTER_ALL {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DEBUG 的本地化字符串。
        /// </summary>
        public static string STR_LOG4NET_FILTER_DEBUG {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_DEBUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug 的本地化字符串。
        /// </summary>
        public static string STR_LOG4NET_FILTER_DEBUG_TT {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_DEBUG_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERROR 的本地化字符串。
        /// </summary>
        public static string STR_LOG4NET_FILTER_ERROR {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string STR_LOG4NET_FILTER_ERROR_TT {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_ERROR_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FATAL 的本地化字符串。
        /// </summary>
        public static string STR_LOG4NET_FILTER_FATAL {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_FATAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fatal Error 的本地化字符串。
        /// </summary>
        public static string STR_LOG4NET_FILTER_FATAL_TT {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_FATAL_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INFO 的本地化字符串。
        /// </summary>
        public static string STR_LOG4NET_FILTER_INFO {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        public static string STR_LOG4NET_FILTER_INFO_TT {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_INFO_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type a filter criteria and activate the filter to customize the display. 的本地化字符串。
        /// </summary>
        public static string STR_LOG4NET_FILTER_TOOLTIP {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WARN 的本地化字符串。
        /// </summary>
        public static string STR_LOG4NET_FILTER_WARN {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_WARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string STR_LOG4NET_FILTER_WARN_TT {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTER_WARN_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sum of actually displayed items (after applying filters). 的本地化字符串。
        /// </summary>
        public static string STR_LOG4NET_FILTERRESULT_TT {
            get {
                return ResourceManager.GetString("STR_LOG4NET_FILTERRESULT_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A Log4net document cannot be edit. This is a read-only viewer document. 的本地化字符串。
        /// </summary>
        public static string STR_LOG4NET_READONY_REASON {
            get {
                return ResourceManager.GetString("STR_LOG4NET_READONY_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Path to Clipboard 的本地化字符串。
        /// </summary>
        public static string STR_MRU_MENUITEM_COPYURL {
            get {
                return ResourceManager.GetString("STR_MRU_MENUITEM_COPYURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open in containing Folder 的本地化字符串。
        /// </summary>
        public static string STR_MRU_MENUITEM_OpenInContainingFolder {
            get {
                return ResourceManager.GetString("STR_MRU_MENUITEM_OpenInContainingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open with Windows Application... 的本地化字符串。
        /// </summary>
        public static string STR_MRU_MENUITEM_OpenWithWindowsApp {
            get {
                return ResourceManager.GetString("STR_MRU_MENUITEM_OpenWithWindowsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string STR_MRU_MENUITEM_Remove {
            get {
                return ResourceManager.GetString("STR_MRU_MENUITEM_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while accessing the plugin directory. 的本地化字符串。
        /// </summary>
        public static string STR_MSG_ACCESS_PLuginDir {
            get {
                return ResourceManager.GetString("STR_MSG_ACCESS_PLuginDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error while loading UML plug-in 的本地化字符串。
        /// </summary>
        public static string STR_MSG_ACCESS_PLuginDir_Caption {
            get {
                return ResourceManager.GetString("STR_MSG_ACCESS_PLuginDir_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugin directory created; no plugins loaded. 的本地化字符串。
        /// </summary>
        public static string STR_MSG_DIRCREATED_NO_PLuginLoaded {
            get {
                return ResourceManager.GetString("STR_MSG_DIRCREATED_NO_PLuginLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The plugin directory was not found. 的本地化字符串。
        /// </summary>
        public static string STR_MSG_DIRCREATED_NO_PLuginLoaded_Caption {
            get {
                return ResourceManager.GetString("STR_MSG_DIRCREATED_NO_PLuginLoaded_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while initializing a plugin found in assembly &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        public static string STR_MSG_ErrorLoadingPlugin {
            get {
                return ResourceManager.GetString("STR_MSG_ErrorLoadingPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error registering highlighting: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        public static string STR_MSG_ErrorRegisteringHighlighting {
            get {
                return ResourceManager.GetString("STR_MSG_ErrorRegisteringHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unexpected problem has occurred while saving the file. 的本地化字符串。
        /// </summary>
        public static string STR_MSG_ErrorSavingFile {
            get {
                return ResourceManager.GetString("STR_MSG_ErrorSavingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while loading plugin assembly &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        public static string STR_MSG_ErrorWhileLoadingPlugin {
            get {
                return ResourceManager.GetString("STR_MSG_ErrorWhileLoadingPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error &apos;{0}&apos;
        ///has occurred while saving a file. 的本地化字符串。
        /// </summary>
        public static string STR_MSG_ErrorWhileSavingAFile {
            get {
                return ResourceManager.GetString("STR_MSG_ErrorWhileSavingAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error &apos;{0}&apos;
        ///has occurred while saving the file:
        ///&apos;{1}&apos; 的本地化字符串。
        /// </summary>
        public static string STR_MSG_ErrorWhileSavingFileX {
            get {
                return ResourceManager.GetString("STR_MSG_ErrorWhileSavingFileX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string STR_MSG_FIND_Caption {
            get {
                return ResourceManager.GetString("STR_MSG_FIND_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no more search results to display. 的本地化字符串。
        /// </summary>
        public static string STR_MSG_FIND_NO_MORE_ITEMS_FOUND {
            get {
                return ResourceManager.GetString("STR_MSG_FIND_NO_MORE_ITEMS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No further occurrence found. 的本地化字符串。
        /// </summary>
        public static string STR_MSG_FIND_NO_MORE_ITEMS_FOUND2 {
            get {
                return ResourceManager.GetString("STR_MSG_FIND_NO_MORE_ITEMS_FOUND2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unexpected error occurred. 的本地化字符串。
        /// </summary>
        public static string STR_MSG_FIND_UNEXPECTED_ERROR {
            get {
                return ResourceManager.GetString("STR_MSG_FIND_UNEXPECTED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please click on the link below to check if this is a known problem.
        ///
        ///Please report this problem if it is not known, yet.
        ///
        ///The problem report should contain the error message below (you can use the copy button)
        ///and a statement about the function/workflow you were using. Attach screenshots or sample files if applicable. 的本地化字符串。
        /// </summary>
        public static string STR_MSG_IssueTrackerText {
            get {
                return ResourceManager.GetString("STR_MSG_IssueTrackerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unhandled Error 的本地化字符串。
        /// </summary>
        public static string STR_MSG_IssueTrackerTitle {
            get {
                return ResourceManager.GetString("STR_MSG_IssueTrackerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugin not loaded. 的本地化字符串。
        /// </summary>
        public static string STR_MSG_PluginNotLoaded {
            get {
                return ResourceManager.GetString("STR_MSG_PluginNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save changes for file &apos;{0}&apos;? 的本地化字符串。
        /// </summary>
        public static string STR_MSG_SaveChangesForFile {
            get {
                return ResourceManager.GetString("STR_MSG_SaveChangesForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A plugin with the specified name has already been loaded. 的本地化字符串。
        /// </summary>
        public static string STR_MSG_UML_PLugin_Duplicate {
            get {
                return ResourceManager.GetString("STR_MSG_UML_PLugin_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not all MiniUml plugins loaded OK. 的本地化字符串。
        /// </summary>
        public static string STR_MSG_UML_PLugin_NOTALL_Loaded {
            get {
                return ResourceManager.GetString("STR_MSG_UML_PLugin_NOTALL_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error loading UML plug-ins 的本地化字符串。
        /// </summary>
        public static string STR_MSG_UML_PLugin_NOTALL_Loaded_Caption {
            get {
                return ResourceManager.GetString("STR_MSG_UML_PLugin_NOTALL_Loaded_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected Error 的本地化字符串。
        /// </summary>
        public static string STR_MSG_Unexpected_Error {
            get {
                return ResourceManager.GetString("STR_MSG_Unexpected_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown document type 的本地化字符串。
        /// </summary>
        public static string STR_MSG_UnknownDocumentType {
            get {
                return ResourceManager.GetString("STR_MSG_UnknownDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unknown error occurred. 的本地化字符串。
        /// </summary>
        public static string STR_Msg_UnknownError {
            get {
                return ResourceManager.GetString("STR_Msg_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unhandled Error 的本地化字符串。
        /// </summary>
        public static string STR_MSG_UnknownError_Caption {
            get {
                return ResourceManager.GetString("STR_MSG_UnknownError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while dispatching unhandled exception 的本地化字符串。
        /// </summary>
        public static string STR_MSG_UnknownError_InErrorDispatcher {
            get {
                return ResourceManager.GetString("STR_MSG_UnknownError_InErrorDispatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error in shut-down process. 的本地化字符串。
        /// </summary>
        public static string STR_MSG_UnknownError_InShutDownProcess {
            get {
                return ResourceManager.GetString("STR_MSG_UnknownError_InShutDownProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application Behaviour 的本地化字符串。
        /// </summary>
        public static string STR_ProgramSettings_ApplicationBehaviour_Header {
            get {
                return ResourceManager.GetString("STR_ProgramSettings_ApplicationBehaviour_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progam Settings... 的本地化字符串。
        /// </summary>
        public static string STR_ProgramSettings_Caption {
            get {
                return ResourceManager.GetString("STR_ProgramSettings_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace 的本地化字符串。
        /// </summary>
        public static string STR_REPLACE_BUTTON_CAPTION {
            get {
                return ResourceManager.GetString("STR_REPLACE_BUTTON_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 percent 的本地化字符串。
        /// </summary>
        public static string STR_SCALE_VIEW_PERCENT {
            get {
                return ResourceManager.GetString("STR_SCALE_VIEW_PERCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % 的本地化字符串。
        /// </summary>
        public static string STR_SCALE_VIEW_PERCENT_SHORT {
            get {
                return ResourceManager.GetString("STR_SCALE_VIEW_PERCENT_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 font size 的本地化字符串。
        /// </summary>
        public static string STR_SCALE_VIEW_POINT {
            get {
                return ResourceManager.GetString("STR_SCALE_VIEW_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pt 的本地化字符串。
        /// </summary>
        public static string STR_SCALE_VIEW_POINT_SHORT {
            get {
                return ResourceManager.GetString("STR_SCALE_VIEW_POINT_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language: 的本地化字符串。
        /// </summary>
        public static string STR_Settings_ApplicationLanguage {
            get {
                return ResourceManager.GetString("STR_Settings_ApplicationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart the application to see the effect of this setting. 的本地化字符串。
        /// </summary>
        public static string STR_Settings_ApplicationLanguage_TT {
            get {
                return ResourceManager.GetString("STR_Settings_ApplicationLanguage_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scroll below document 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_AllowScrollBelowDocument {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_AllowScrollBelowDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Percent 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_CharacterSizeInPercent {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_CharacterSizeInPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Points 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_CharacterSizeInPoints {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_CharacterSizeInPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adjust text editor character size 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_CharacterSizeSectionLabel {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_CharacterSizeSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Ruler 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_ColumnRulerSectionLabel {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_ColumnRulerSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert tabulator character into space character 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_ConvertTabToSpace {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_ConvertTabToSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut and copy current line of text 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_CutCopyWholeLine {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_CutCopyWholeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Email hyperlinks 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_EnableEmailHyperlinks {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_EnableEmailHyperlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show file hyperlinks 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_EnableFileHyperlinks {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_EnableFileHyperlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IME Support 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_EnableImeSupport {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_EnableImeSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rectangular selection (ALT+Shift or ALT+Mouse selection) 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_EnableRectangularSelection {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_EnableRectangularSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text drag &amp; drop 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_EnableTextDragDrop {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_EnableTextDragDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 virtual space 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_EnableVirtualSpace {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_EnableVirtualSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hyperlinks 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_Hyperlink_Section {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_Hyperlink_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inherit word wrap indentation 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_InheritWordWrapIndentation {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_InheritWordWrapIndentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Require Control key for hyperlink click 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_RequireControlModifierForHyperlinkClick {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_RequireControlModifierForHyperlinkClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Editor Options 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_Section_Label {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_Section_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show box for control characters 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_ShowBoxForControlChar {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_ShowBoxForControlChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show column ruler 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_ShowColumnRulerOption {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_ShowColumnRulerOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show end of line 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_ShowEndOfLine {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_ShowEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show WWW hyperlinks 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_ShowHyperlinks {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_ShowHyperlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Spaces 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_ShowSpaces {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_ShowSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Tabs 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_ShowTabs {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_ShowTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Word Wrap Text 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Editor_WordWrap {
            get {
                return ResourceManager.GetString("STR_Settings_Editor_WordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Favourites (not sorted) 的本地化字符串。
        /// </summary>
        public static string STR_Settings_MRU_Pin_At_Current_Position {
            get {
                return ResourceManager.GetString("STR_Settings_MRU_Pin_At_Current_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin entries at the beginning of the list 的本地化字符串。
        /// </summary>
        public static string STR_Settings_MRU_Pin_At_StartOption {
            get {
                return ResourceManager.GetString("STR_Settings_MRU_Pin_At_StartOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Most Recent Files (MRU) mode 的本地化字符串。
        /// </summary>
        public static string STR_Settings_MRU_Section_Label {
            get {
                return ResourceManager.GetString("STR_Settings_MRU_Section_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore last user session when application starts 的本地化字符串。
        /// </summary>
        public static string STR_Settings_RestoreUserSession {
            get {
                return ResourceManager.GetString("STR_Settings_RestoreUserSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run Edi only once 的本地化字符串。
        /// </summary>
        public static string STR_Settings_RunEdiOnlyOnce {
            get {
                return ResourceManager.GetString("STR_Settings_RunEdiOnlyOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alternate background color 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Text2HTML_AlternatingBackground {
            get {
                return ResourceManager.GetString("STR_Settings_Text2HTML_AlternatingBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text to HTML Export 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Text2HTML_GroupHeader {
            get {
                return ResourceManager.GetString("STR_Settings_Text2HTML_GroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show line numbers 的本地化字符串。
        /// </summary>
        public static string STR_Settings_Text2HTML_ShowLineNumbers {
            get {
                return ResourceManager.GetString("STR_Settings_Text2HTML_ShowLineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open file... 的本地化字符串。
        /// </summary>
        public static string STR_STARTPAGE_FILEOPEN_TT {
            get {
                return ResourceManager.GetString("STR_STARTPAGE_FILEOPEN_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Page 的本地化字符串。
        /// </summary>
        public static string STR_STARTPAGE_TITLE {
            get {
                return ResourceManager.GetString("STR_STARTPAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visit the Internet home page of this application 的本地化字符串。
        /// </summary>
        public static string STR_STARTPAGE_VISITPROJECTHOMEPAGE_TT {
            get {
                return ResourceManager.GetString("STR_STARTPAGE_VISITPROJECTHOMEPAGE_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to Edi. Review this page to get started with this editor application. 的本地化字符串。
        /// </summary>
        public static string STR_STARTPAGE_WELCOME_TT {
            get {
                return ResourceManager.GetString("STR_STARTPAGE_WELCOME_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready. 的本地化字符串。
        /// </summary>
        public static string STR_StatusBar_Ready {
            get {
                return ResourceManager.GetString("STR_StatusBar_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encoding of the text in the current document 的本地化字符串。
        /// </summary>
        public static string STR_StatusBar_Textencoding_TT {
            get {
                return ResourceManager.GetString("STR_StatusBar_Textencoding_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X: 的本地化字符串。
        /// </summary>
        public static string STR_StatusBar_X_Coord_Label {
            get {
                return ResourceManager.GetString("STR_StatusBar_X_Coord_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column of the cursor in the current document 的本地化字符串。
        /// </summary>
        public static string STR_StatusBar_X_Coord_Label_TT {
            get {
                return ResourceManager.GetString("STR_StatusBar_X_Coord_Label_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y: 的本地化字符串。
        /// </summary>
        public static string STR_StatusBar_Y_Coord_Label {
            get {
                return ResourceManager.GetString("STR_StatusBar_Y_Coord_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row of the cursor in the current document 的本地化字符串。
        /// </summary>
        public static string STR_StatusBar_Y_Coord_Label_TT {
            get {
                return ResourceManager.GetString("STR_StatusBar_Y_Coord_Label_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theming Error 的本地化字符串。
        /// </summary>
        public static string STR_THEMING_CAPTION {
            get {
                return ResourceManager.GetString("STR_THEMING_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find Path to:
        ///&apos;{0}&apos;
        ///
        ///Please make sure this module is accessible. 的本地化字符串。
        /// </summary>
        public static string STR_THEMING_MSG_CANNOT_FIND_PATH {
            get {
                return ResourceManager.GetString("STR_THEMING_MSG_CANNOT_FIND_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a text highlighting pattern 的本地化字符串。
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_HighlightingDefinition_TT {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_HighlightingDefinition_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show End of Line 的本地化字符串。
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowEndOfLine {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show end of line 的本地化字符串。
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowEndOfLine_TT {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowEndOfLine_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Line Numbers 的本地化字符串。
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowLineNumbers {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowLineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show line numbers 的本地化字符串。
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowLineNumbers_TT {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowLineNumbers_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Spaces 的本地化字符串。
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowSpaces {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show space characters 的本地化字符串。
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowSpaces_TT {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowSpaces_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Tabs 的本地化字符串。
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowTabs {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show tabulator characters 的本地化字符串。
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowTabs_TT {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowTabs_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Word Wrap 的本地化字符串。
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_WordWrap {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_WordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrap text around document view 的本地化字符串。
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_WordWrap_TT {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_WordWrap_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tool Windows 的本地化字符串。
        /// </summary>
        public static string STR_VIEW_TOOLWINDOWS {
            get {
                return ResourceManager.GetString("STR_VIEW_TOOLWINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Columns 的本地化字符串。
        /// </summary>
        public static string STR_YALVLIb_Columns_MenuLabel {
            get {
                return ResourceManager.GetString("STR_YALVLIb_Columns_MenuLabel", resourceCulture);
            }
        }
    }
}
